CREATE SEQUENCE seq_customer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_account START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE seq_transaction START WITH 5001 INCREMENT BY 1;
CREATE SEQUENCE seq_loan START WITH 2001 INCREMENT BY 1;